spring:
  application:
    name: medvoll
  datasource:
    url: jdbc:postgresql://localhost:5432/alura
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    format-sql: true
  hibernate:
    dialect: org.hibernate.dialect.PostgreSQLDialect
